<?php
/**
 * ml_image - Attach AI-generated image to a publication
 *
 * Receives a base64-encoded image (generated by Claude) and attaches it
 * as the featured image (post thumbnail) of a publication.
 *
 * @package MCP_No_Headless
 * @since 3.2.31
 */

namespace MCP_No_Headless\MCP\Core\Tools;

use MCP_No_Headless\MCP\Core\Tool_Response;

class Image {

    const TOOL_NAME = 'ml_image';

    /**
     * Execute image attachment
     *
     * @param array $args Tool arguments
     * @param int $user_id Current user ID
     * @return array Result
     */
    public static function execute(array $args, int $user_id): array {
        $publication_id = isset($args['publication_id']) ? (int) $args['publication_id'] : 0;
        $image_base64 = $args['image_base64'] ?? '';
        $alt_text = $args['alt'] ?? '';
        $caption = $args['caption'] ?? '';

        // Validate publication_id
        if (!$publication_id) {
            return Tool_Response::validation_error(
                'publication_id requis',
                ['publication_id' => 'ID de la publication à illustrer']
            );
        }

        // Validate publication exists
        $post = get_post($publication_id);
        if (!$post || $post->post_type !== 'publication') {
            return Tool_Response::validation_error(
                "Publication #$publication_id introuvable",
                ['publication_id' => 'Vérifiez que la publication existe']
            );
        }

        // Validate base64 image
        if (empty($image_base64)) {
            return Tool_Response::validation_error(
                'image_base64 requis',
                ['image_base64' => 'Image encodée en base64 (PNG ou JPEG)']
            );
        }

        // Strip data URI prefix if present (e.g., "data:image/png;base64,...")
        if (preg_match('/^data:image\/(\w+);base64,/', $image_base64, $matches)) {
            $extension = $matches[1] === 'jpeg' ? 'jpg' : $matches[1];
            $image_base64 = preg_replace('/^data:image\/\w+;base64,/', '', $image_base64);
        } else {
            $extension = 'png'; // default
        }

        // Decode base64
        $image_data = base64_decode($image_base64, true);
        if ($image_data === false || strlen($image_data) < 100) {
            return Tool_Response::validation_error(
                'Image base64 invalide',
                ['image_base64' => 'Le décodage base64 a échoué']
            );
        }

        // Detect actual image type from binary
        $finfo = new \finfo(FILEINFO_MIME_TYPE);
        $mime = $finfo->buffer($image_data);
        $allowed = [
            'image/png' => 'png',
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
        ];

        if (!isset($allowed[$mime])) {
            return Tool_Response::validation_error(
                "Type d'image non supporté: $mime",
                ['image_base64' => 'Formats acceptés: PNG, JPEG, WebP']
            );
        }
        $extension = $allowed[$mime];

        // Save to temp file
        $upload_dir = wp_upload_dir();
        $filename = 'ml_image_' . $publication_id . '_' . uniqid() . '.' . $extension;
        $tmp_path = $upload_dir['path'] . '/' . $filename;

        if (file_put_contents($tmp_path, $image_data) === false) {
            return Tool_Response::error('upload_failed', "Impossible d'écrire le fichier image");
        }

        // Create WP attachment
        require_once(ABSPATH . 'wp-admin/includes/image.php');

        $attachment = [
            'post_mime_type' => $mime,
            'post_title' => $alt_text ?: ('Image - ' . get_the_title($publication_id)),
            'post_content' => '',
            'post_excerpt' => $caption,
            'post_status' => 'inherit',
            'post_parent' => $publication_id,
        ];

        $attach_id = wp_insert_attachment($attachment, $tmp_path, $publication_id);

        if (is_wp_error($attach_id)) {
            @unlink($tmp_path);
            return Tool_Response::error('attachment_failed', $attach_id->get_error_message());
        }

        // Generate metadata (thumbnails, sizes, etc.)
        $attach_data = wp_generate_attachment_metadata($attach_id, $tmp_path);
        wp_update_attachment_metadata($attach_id, $attach_data);

        // Set alt text
        if ($alt_text) {
            update_post_meta($attach_id, '_wp_attachment_image_alt', sanitize_text_field($alt_text));
        }

        // Set as featured image (Picasso)
        set_post_thumbnail($publication_id, $attach_id);

        // Build response
        $image_url = wp_get_attachment_url($attach_id);

        return [
            'ok' => true,
            'message' => "Image attachée à la publication #$publication_id",
            'data' => [
                'attachment_id' => $attach_id,
                'publication_id' => $publication_id,
                'url' => $image_url,
                'mime' => $mime,
                'size' => strlen($image_data),
            ],
        ];
    }
}
